services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:17-alpine
    container_name: okrika_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: '-c password_encryption=scram-sha-256 -A scram-sha-256'
    ports:
      - '0.0.0.0:${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - okrika_network

  # Redis Service
  redis:
    image: redis:8-alpine
    container_name: okrika_redis
    restart: always
    ports:
      - '0.0.0.0:${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - okrika_network

volumes:
  postgres_data:
  redis_data:

networks:
  okrika_network:
    driver: bridge
